Add NATS 2.9.17 announcement post
nats-io/nats-site pull request #833
Opened 2023-05-20 12:35 UTC by bruth

The changes to the 2.9.16 post was only to fix the anchor links, but would appreciate a review on the 2.9.17 for correctness in explanation and of course grammar/readability 🙂

2023-05-20 13:46 UTC, wallyqs commented on content/blog/nats-server-2.9.17-release.md
> +It is not uncommon for preferring UTC time values, especially in system spanning multiple time zones. However, did you know that calling the `time.Now().UTC()` will resort in throwing away an interna
`s/conccurrently/concurrently`

2023-05-20 14:47 UTC, gcolliso commented
In my previews, the anchor links at the top to Health monitor improvements & Monotonic time calculations aren't showing a link.

2023-05-20 16:37 UTC, philpennock requested changes
English be cray-cray.

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +As part of the [P99 peformance work in the 2.9.16 release](https://nats.io/blog/nats-server-2.9.16-release/#-p99-performance), a regression was introduced, resulting in [faulty subscription behavior
"received" -> "receiving"

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +However, the upside of addressing this issue resulted in more (correct) optimizations for the WebSocket transport, including reducing the overall memory footprint and switching to a [faster compressi
Incompatible tense changes with "resulted" there. Suggest: "... this issue is more ..."

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +The job of the `/healthz` endpoint is to return `200 OK` when the server is ready for client connections and, if JetStream is enabled, all of the assets (streams and consumers) on the server have bee
Incompatible tense change. "was performed" to "has been performed". Present perfect tense vs past perfect tense.

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +In rare situations, for clusters with a large number of assets, or if the asset sizes are large, it was possible for given server to get stuck and never finish the internal checks, therefore never be
"for given server" ... might use "for a given server" but probably best to just be "for a server"

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +This release brings an internal routine that periodically checks whether all assets have checked and restarts the ones that have become stuck. This obviates the need to force restart the server, resu
Assets are checked, they don't do the checking. "all assets have been checked"

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +This is possible by configuring the leafnodes as a local [cluster](https://docs.nats.io/running-a-nats-service/configuration/clustering) while each node also having the [`remotes`](https://docs.nats.
"each node also having" : "having" -> "has"

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +As the scale of edge deployments increase, so does the need to optimize how real-time propagation of _subject-interest_. Where it was common to have many single leafnode deployments, having clusters
Because it's "the scale of X", it's singular, so "increase" -> "increases". Then, end of this sentence, you're missing the verb. Insert "happens".

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +This release brings the first of a series of optimizations for increasingly large-scale fleets. This initial improvement accounts for the fact that interest-propagation updates only need to be sent t
Well, it does need to reach all of them, it's just that the out-of-cluster sender only needs to directly send it to one and can then hand off the responsibility. Which is clear enough in what you wrote if you understand the system as we do, but for release notes might need minor adjustment.

I think the clearest fix is also the simplest, insert "directly": "only needs to be directly sent to".

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +Although this improvement fixes a number of timing edge cases internally to the server, this section will serve as a Pro-Tip for anyone relying on Go's [time](https://pkg.go.dev/time) package for cal
"internally" -> "internal"

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +It is not uncommon for preferring UTC time values, especially in system spanning multiple time zones. However, did you know that calling the `time.Now().UTC()` will result in throwing away an interna
"for preferring" -> "to prefer".

Then the second sentence needs to end in a question mark, not a full stop.

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +Below is an example output. Note the local times are differentiated by that `m=+` value shown in the output with a calculated 83ns difference between the times. The second set of times are converted
The "with a calculated" is an additional comment, probably best to have a comma before it; however this one can be correct as-is if you mean that the actual delta is part of the differentiation. I'd insert the comma, were it me.

Near the end: "different" -> "difference" to get the noun.

2023-05-20 16:37 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +The NATS team wants to reiterate our appreciation to all contributors in this release, including those testing and providing feedback during the release cycle. As a reminder, nightly builds on the `m
Might want to make clear that main is 2.9.x here?

2023-05-22 13:36 UTC, philpennock approved these changes

2023-05-22 13:36 UTC, philpennock commented on content/blog/nats-server-2.9.17-release.md
> +The NATS team wants to reiterate our appreciation to all contributors in this release, including those testing and providing feedback during the release cycle. Nightly builds on the `main` branch, tr
nb: all our series are minor series, 2.10 is a minor series too.  Did you mean "stable series"?

2023-05-22 13:40 UTC, philpennock approved these changes

2023-05-22 14:51 UTC, gcolliso approved these changes
lgtm

2023-05-22 14:51 UTC, merged